# ============================================
# configs/production.yaml - 生产部署配置
# ============================================

model:
  channels: [64, 128, 256, 512]
  dropout: 0.0                          # 推理时不需要dropout

diffusion:
  sampling:
    method: ddim
    ddim_steps: 30                      # 平衡质量和速度
    ddim_eta: 0.0                       # 确定性生成
    clip_denoised: true

inference:
  batch_size: 4                        # 批量处理
  num_samples: 1
  seed: null                            # 随机种子（多样性）

system:
  device: cuda
  cudnn_benchmark: true                 # 优化推理速度
  deterministic: false                  # 不需要确定性

webapp:
  gradio:
    server_name: "0.0.0.0"
    server_port: 7860
    share: false
    auth: ["admin", "password123"]      # 生产环境需要认证
    
  api:
    host: "0.0.0.0"
    port: 8000
    workers: 4                          # 多进程处理请求